// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vddxueqeiusevpncfmsa.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZkZHh1ZXFlaXVzZXZwbmNmbXNhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjY1Nzc1ODQsImV4cCI6MjA4MjE1MzU4NH0.2VqCEMl-7OwVoGj86L2c_nfkxtmEE73fPLANVyXxP4o";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});